# Generated by Django 5.1.1 on 2024-10-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('comp_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.EmailField(max_length=20)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
