# Generated by Django 5.1.1 on 2024-10-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.EmailField(max_length=20, unique=True),
        ),
    ]
