# Generated by Django 5.1.1 on 2024-10-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='comp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
