# Generated by Django 5.1.1 on 2024-11-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_usuario_created_at_alter_usuario_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numero_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_item', models.TextField()),
                ('mesa', models.IntegerField()),
                ('status_pedido', models.CharField(max_length=50)),
                ('qtd', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'emp1.pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('precos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem_item', models.ImageField(blank=True, null=True, upload_to='static/assets/images')),
            ],
        ),
    ]
